$(document).ready(function() {
	$('#about').click(function(){
		$('.about').fadeToggle();
		$('#official-logo').fadeToggle();
		$('#work').fadeToggle();
		$('#contact').fadeToggle();
	});
	$('#work').click(function(){
		$('.work').fadeToggle();
		$('#official-logo').fadeToggle();
		$('#about').fadeToggle();
		$('#contact').fadeToggle();
	});
	$('#contact').click(function(){
		$('.contact').fadeToggle();
		$('#official-logo').fadeToggle();
		$('#about').fadeToggle();
		$('#work').fadeToggle();
	});
});